enum colors {
  TEXT_1 = "#fff;",
  TEXT_BLACK = "black",
  TEXT_GRAY = "#909096",
  TEXT_VIVID_CYAN = "#08fdd8",
  TEXT_YELLOWGREEN = "yellowgreen",
  TEXT_WHITE = "white",
  TEXT_ORANGE = "orange",
  TEXT_GREEN = "#00B347",
  TEXT_RED = "red",
  TEXT_BLUE = "#009CB4",
  MAIN_BLUE = "#009CB4",

  BORDER_GRAY = "#282828",
  BORDER_BLUE = "#009CB4",

  BACKGROUND_BODY = "#313146",
  BACKGROUND_BLACK = "#181818",
  BACKGROUND_WHITE = "#fff",
  BACKGROUND_VIVID_CYAN = "#08fdd8",
  BACKGROUND_DARK_GRAY = "#181818",
  BACKGROUND_WHITESMOKE = "whitesmoke",
  BACKGROUND_RED = "#FD2155",
  BACKGROUND_ORANGE = "orange",
  BACKGROUND_BLUE = "#0064eb",
  BACKGROUND_LIGHT_GRAY = "#808080",
  MODAL_BACKGROUND_OPACITY = "rgba(64, 63, 77, 0.7)",
  BOX_SHADOW_DARK = "rgba(0, 0, 0, 0.6)",
  BOX_SHADOW = "rgba(0, 0, 0, 0.06)",
  WHITE = "white",
  BLACK = "black",
  YELLOW = "yellow",
  GRAY = "#909096",
  COLOR_RED = "#FD2155",
}

export default colors;
